export {
  createHostDaemonLocalClient,
  DEFAULT_HOST_DAEMON_LOCAL_BIND_HOST,
  hostPlatformSchema,
  openInTargetRequestSchema,
  PATHS_EXIST_MAX_PATHS,
  pathsExistRequestSchema,
  pathsExistResponseSchema,
  pickFolderResponseSchema,
  providerCliInstallActionKindSchema,
  providerCliInstallActionKindValues,
  providerCliInstallActionSchema,
  providerCliInstallCommandKindSchema,
  providerCliInstallCommandKindValues,
  providerCliInstallCompletedEventSchema,
  providerCliInstallErrorEventSchema,
  providerCliInstallEventSchema,
  providerCliInstallOutputEventSchema,
  providerCliInstallOutputStreamSchema,
  providerCliInstallOutputStreamValues,
  providerCliInstallRequestSchema,
  providerCliInstallSourceSchema,
  providerCliInstallSourceValues,
  providerCliInstallStartedEventSchema,
  providerCliKeySchema,
  providerCliKeyValues,
  providerCliStatusResponseSchema,
  providerCliStatusSchema,
  statusResponseSchema,
  workspaceOpenTargetCapabilitiesSchema,
  workspaceOpenTargetIdSchema,
  workspaceOpenTargetIdValues,
  workspaceOpenTargetSchema,
  workspaceOpenTargetsResponseSchema,
} from "./local.js";
export type {
  HostDaemonLocalRoutes,
  HostDaemonLocalSchema,
  HostPlatform,
  OpenInTargetRequest,
  PathsExistRequest,
  PathsExistResponse,
  PickFolderResponse,
  ProviderCliInstallAction,
  ProviderCliInstallActionKind,
  ProviderCliInstallCompletedEvent,
  ProviderCliInstallEvent,
  ProviderCliInstallRequest,
  ProviderCliInstallSource,
  ProviderCliKey,
  ProviderCliStatus,
  ProviderCliStatusResponse,
  StatusResponse,
  WorkspaceOpenTarget,
  WorkspaceOpenTargetCapabilities,
  WorkspaceOpenTargetId,
  WorkspaceOpenTargetsResponse,
} from "./local.js";

export { HOST_DAEMON_PROTOCOL_VERSION } from "./protocol-version.js";

export {
  workspaceResolutionFailureCodeSchema,
  workspaceResolutionFailureSchema,
} from "./workspace-resolution-failure.js";
export type {
  WorkspaceResolutionFailure,
  WorkspaceResolutionFailureCode,
} from "./workspace-resolution-failure.js";
